<?php

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityFormInterface;
use Drupal\gr_core\Entity\Category;
use Drupal\gr_core\Entity\Difficulty;
use Drupal\gr_core\Entity\Season;
use Drupal\gr_core\Entity\DishType;
use Drupal\gr_core\Entity\Ingredient;
use Drupal\gr_core\Entity\File;
use Drupal\gr_core\Entity\Recipe;

function gr_core_entity_bundle_info_alter(array &$bundles): void {
  if (isset($bundles['taxonomy_term']['category'])) {
    $bundles['taxonomy_term']['category']['class'] = Category::class;
  }
  if (isset($bundles['taxonomy_term']['difficulty'])) {
    $bundles['taxonomy_term']['difficulty']['class'] = Difficulty::class;
  }
  if (isset($bundles['taxonomy_term']['season'])) {
    $bundles['taxonomy_term']['season']['class'] = Season::class;
  }
  if (isset($bundles['taxonomy_term']['dish_type'])) {
    $bundles['taxonomy_term']['dish_type']['class'] = DishType::class;
  }
  if (isset($bundles['node']['ingredient'])) {
    $bundles['node']['ingredient']['class'] = Ingredient::class;
  }
  if (isset($bundles['file']['file'])) {
    $bundles['file']['file']['class'] = File::class;
  }
  if (isset($bundles['node']['recipe'])) {
    $bundles['node']['recipe']['class'] = Recipe::class;
  }
}