<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function quantity_field_theme($existing, $type, $theme, $path) {
  return [
    'quantity_field_css' => [
      'css' => [
        'css/quantity_field.css',
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function quantity_field_form_field_ui_field_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'quantity_field/quantity_field_css';
}
