_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: fr
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  ckeditor_bs_grid: 0
  comment: 0
  config: 0
  config_pages: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  fontawesome: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  imagemagick: 0
  language: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  pager_serializer: 0
  path: 0
  path_alias: 0
  redirect: 0
  rest: 0
  rest_menu_items: 0
  scheduler: 0
  search: 0
  search_api: 0
  serialization: 0
  shortcut: 0
  sophron: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  workflows: 0
  ds: 1
  pathauto: 1
  ds_extras: 2
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  seven: 0
  adminimal_theme: 0
profile: standard
