_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: fr
uuid: f45e59eb-b8af-4b20-b9be-d41d19430c0b
name: 'Good Recipes'
mail: maninchristophe@yahoo.com
slogan: ''
page:
  403: ''
  404: ''
  front: /admin/front
admin_compact_mode: false
weight_select_max: 100
default_langcode: fr
mail_notification: null
